env:
  browser: true
  es6: true
  node: true
overrides:
  - files: ['*.js', '*.jsx', '*.ts', '*.tsx']
    extends: 'standard-with-typescript'
extends:
  - 'plugin:react/recommended'
  - standard-with-typescript
settings:
  react:
    version: detect
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {}
