#!/bin/bash

BRANCH=$(git branch --show-current)

if [ $BRANCH == "master" ]; then
  STACK_NAME=inside-story
else
  STACK_NAME=$BRANCH
fi

echo "Retrieving stack description..."
STACK_OUTPUT=`aws cloudformation describe-stacks --stack-name $STACK_NAME | jq ".Stacks[0].Outputs"`
echo "Done"

for ENV in development production; do
  # gatsby uses a particular scheme for organizing env files;
  # we treat all env files the same in accordance with 12-factor app guidelines
  cp -f -v .env .env.$ENV
  SITE_BUCKET=`echo $STACK_OUTPUT | jq -r '.[] | select(.OutputKey == "BucketName").OutputValue'`
  echo "SITE_BUCKET=$SITE_BUCKET" >> .env.$ENV
  USER_POOL_NAME=$STACK_NAME
  echo "USER_POOL_NAME=$USER_POOL_NAME" >> .env.$ENV
  SITE_DOMAIN=`echo $STACK_OUTPUT | jq -r '.[] | select(.OutputKey == "SiteDomain").OutputValue'`
  echo "SITE_DOMAIN=$SITE_DOMAIN" >> .env.$ENV
  VIDEO_DOMAIN=`echo $STACK_OUTPUT | jq -r '.[] | select(.OutputKey == "VideoDomain").OutputValue'`
  echo "VIDEO_DOMAIN=$VIDEO_DOMAIN" >> .env.$ENV
  SIGNER_DOMAIN=`echo $STACK_OUTPUT | jq -r '.[] | select(.OutputKey == "SignerDomain").OutputValue'`
  echo "SIGNER_DOMAIN=$SIGNER_DOMAIN" >> .env.$ENV
  USER_POOL_CLIENT_ID=`echo $STACK_OUTPUT | jq -r '.[] | select(.OutputKey == "UserPoolClientId").OutputValue'`
  echo "USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID" >> .env.$ENV
  VIDEO_ASSET_ORIGIN_ACCESS_IDENTITY=`echo $STACK_OUTPUT | jq -r '.[] | select(.OutputKey == "VideoAssetOriginAccessIdentity").OutputValue'`
  echo "VIDEO_ASSET_ORIGIN_ACCESS_IDENTITY=$VIDEO_ASSET_ORIGIN_ACCESS_IDENTITY" >> .env.$ENV
done
