name: 'Lint'
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: NPM_CONFIG_LEGACY_PEER_DEPS=true npm install
      - run: npm run lint
